// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: recorder.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RecordGetterClient is the client API for RecordGetter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecordGetterClient interface {
	NewRecord(ctx context.Context, in *NewRecordRequest, opts ...grpc.CallOption) (*NewRecordResponse, error)
}

type recordGetterClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordGetterClient(cc grpc.ClientConnInterface) RecordGetterClient {
	return &recordGetterClient{cc}
}

func (c *recordGetterClient) NewRecord(ctx context.Context, in *NewRecordRequest, opts ...grpc.CallOption) (*NewRecordResponse, error) {
	out := new(NewRecordResponse)
	err := c.cc.Invoke(ctx, "/recorder.RecordGetter/NewRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordGetterServer is the server API for RecordGetter service.
// All implementations should embed UnimplementedRecordGetterServer
// for forward compatibility
type RecordGetterServer interface {
	NewRecord(context.Context, *NewRecordRequest) (*NewRecordResponse, error)
}

// UnimplementedRecordGetterServer should be embedded to have forward compatible implementations.
type UnimplementedRecordGetterServer struct {
}

func (UnimplementedRecordGetterServer) NewRecord(context.Context, *NewRecordRequest) (*NewRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewRecord not implemented")
}

// UnsafeRecordGetterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecordGetterServer will
// result in compilation errors.
type UnsafeRecordGetterServer interface {
	mustEmbedUnimplementedRecordGetterServer()
}

func RegisterRecordGetterServer(s grpc.ServiceRegistrar, srv RecordGetterServer) {
	s.RegisterService(&RecordGetter_ServiceDesc, srv)
}

func _RecordGetter_NewRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordGetterServer).NewRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recorder.RecordGetter/NewRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordGetterServer).NewRecord(ctx, req.(*NewRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecordGetter_ServiceDesc is the grpc.ServiceDesc for RecordGetter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecordGetter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recorder.RecordGetter",
	HandlerType: (*RecordGetterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewRecord",
			Handler:    _RecordGetter_NewRecord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recorder.proto",
}
