// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: recorder.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewRecordRequest) Reset() {
	*x = NewRecordRequest{}
	mi := &file_recorder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewRecordRequest) ProtoMessage() {}

func (x *NewRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recorder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewRecordRequest.ProtoReflect.Descriptor instead.
func (*NewRecordRequest) Descriptor() ([]byte, []int) {
	return file_recorder_proto_rawDescGZIP(), []int{0}
}

type NewRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewRecordResponse) Reset() {
	*x = NewRecordResponse{}
	mi := &file_recorder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewRecordResponse) ProtoMessage() {}

func (x *NewRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recorder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewRecordResponse.ProtoReflect.Descriptor instead.
func (*NewRecordResponse) Descriptor() ([]byte, []int) {
	return file_recorder_proto_rawDescGZIP(), []int{1}
}

type GetQualityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReleaseId     int64                  `protobuf:"varint,1,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQualityRequest) Reset() {
	*x = GetQualityRequest{}
	mi := &file_recorder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQualityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQualityRequest) ProtoMessage() {}

func (x *GetQualityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recorder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQualityRequest.ProtoReflect.Descriptor instead.
func (*GetQualityRequest) Descriptor() ([]byte, []int) {
	return file_recorder_proto_rawDescGZIP(), []int{2}
}

func (x *GetQualityRequest) GetReleaseId() int64 {
	if x != nil {
		return x.ReleaseId
	}
	return 0
}

type GetQualityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         int32                  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQualityResponse) Reset() {
	*x = GetQualityResponse{}
	mi := &file_recorder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQualityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQualityResponse) ProtoMessage() {}

func (x *GetQualityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recorder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQualityResponse.ProtoReflect.Descriptor instead.
func (*GetQualityResponse) Descriptor() ([]byte, []int) {
	return file_recorder_proto_rawDescGZIP(), []int{3}
}

func (x *GetQualityResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_recorder_proto protoreflect.FileDescriptor

const file_recorder_proto_rawDesc = "" +
	"\n" +
	"\x0erecorder.proto\x12\brecorder\"\x12\n" +
	"\x10NewRecordRequest\"\x13\n" +
	"\x11NewRecordResponse\"2\n" +
	"\x11GetQualityRequest\x12\x1d\n" +
	"\n" +
	"release_id\x18\x01 \x01(\x03R\treleaseId\"*\n" +
	"\x12GetQualityResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x05R\x05score2T\n" +
	"\fRecordGetter\x12D\n" +
	"\tNewRecord\x12\x1a.recorder.NewRecordRequest\x1a\x1b.recorder.NewRecordResponse2Y\n" +
	"\x0eQualityService\x12G\n" +
	"\n" +
	"GetQuality\x12\x1b.recorder.GetQualityRequest\x1a\x1c.recorder.GetQualityResponseB(Z&github.com/brotherlogic/recorder/protob\x06proto3"

var (
	file_recorder_proto_rawDescOnce sync.Once
	file_recorder_proto_rawDescData []byte
)

func file_recorder_proto_rawDescGZIP() []byte {
	file_recorder_proto_rawDescOnce.Do(func() {
		file_recorder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recorder_proto_rawDesc), len(file_recorder_proto_rawDesc)))
	})
	return file_recorder_proto_rawDescData
}

var file_recorder_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_recorder_proto_goTypes = []any{
	(*NewRecordRequest)(nil),   // 0: recorder.NewRecordRequest
	(*NewRecordResponse)(nil),  // 1: recorder.NewRecordResponse
	(*GetQualityRequest)(nil),  // 2: recorder.GetQualityRequest
	(*GetQualityResponse)(nil), // 3: recorder.GetQualityResponse
}
var file_recorder_proto_depIdxs = []int32{
	0, // 0: recorder.RecordGetter.NewRecord:input_type -> recorder.NewRecordRequest
	2, // 1: recorder.QualityService.GetQuality:input_type -> recorder.GetQualityRequest
	1, // 2: recorder.RecordGetter.NewRecord:output_type -> recorder.NewRecordResponse
	3, // 3: recorder.QualityService.GetQuality:output_type -> recorder.GetQualityResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_recorder_proto_init() }
func file_recorder_proto_init() {
	if File_recorder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recorder_proto_rawDesc), len(file_recorder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_recorder_proto_goTypes,
		DependencyIndexes: file_recorder_proto_depIdxs,
		MessageInfos:      file_recorder_proto_msgTypes,
	}.Build()
	File_recorder_proto = out.File
	file_recorder_proto_goTypes = nil
	file_recorder_proto_depIdxs = nil
}
