// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: recorder.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecordGetter_NewRecord_FullMethodName = "/recorder.RecordGetter/NewRecord"
)

// RecordGetterClient is the client API for RecordGetter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecordGetterClient interface {
	NewRecord(ctx context.Context, in *NewRecordRequest, opts ...grpc.CallOption) (*NewRecordResponse, error)
}

type recordGetterClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordGetterClient(cc grpc.ClientConnInterface) RecordGetterClient {
	return &recordGetterClient{cc}
}

func (c *recordGetterClient) NewRecord(ctx context.Context, in *NewRecordRequest, opts ...grpc.CallOption) (*NewRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewRecordResponse)
	err := c.cc.Invoke(ctx, RecordGetter_NewRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordGetterServer is the server API for RecordGetter service.
// All implementations should embed UnimplementedRecordGetterServer
// for forward compatibility.
type RecordGetterServer interface {
	NewRecord(context.Context, *NewRecordRequest) (*NewRecordResponse, error)
}

// UnimplementedRecordGetterServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecordGetterServer struct{}

func (UnimplementedRecordGetterServer) NewRecord(context.Context, *NewRecordRequest) (*NewRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NewRecord not implemented")
}
func (UnimplementedRecordGetterServer) testEmbeddedByValue() {}

// UnsafeRecordGetterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecordGetterServer will
// result in compilation errors.
type UnsafeRecordGetterServer interface {
	mustEmbedUnimplementedRecordGetterServer()
}

func RegisterRecordGetterServer(s grpc.ServiceRegistrar, srv RecordGetterServer) {
	// If the following call panics, it indicates UnimplementedRecordGetterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecordGetter_ServiceDesc, srv)
}

func _RecordGetter_NewRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordGetterServer).NewRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordGetter_NewRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordGetterServer).NewRecord(ctx, req.(*NewRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecordGetter_ServiceDesc is the grpc.ServiceDesc for RecordGetter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecordGetter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recorder.RecordGetter",
	HandlerType: (*RecordGetterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewRecord",
			Handler:    _RecordGetter_NewRecord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recorder.proto",
}

const (
	QualityService_GetQuality_FullMethodName = "/recorder.QualityService/GetQuality"
)

// QualityServiceClient is the client API for QualityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QualityServiceClient interface {
	GetQuality(ctx context.Context, in *GetQualityRequest, opts ...grpc.CallOption) (*GetQualityResponse, error)
}

type qualityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQualityServiceClient(cc grpc.ClientConnInterface) QualityServiceClient {
	return &qualityServiceClient{cc}
}

func (c *qualityServiceClient) GetQuality(ctx context.Context, in *GetQualityRequest, opts ...grpc.CallOption) (*GetQualityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQualityResponse)
	err := c.cc.Invoke(ctx, QualityService_GetQuality_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QualityServiceServer is the server API for QualityService service.
// All implementations should embed UnimplementedQualityServiceServer
// for forward compatibility.
type QualityServiceServer interface {
	GetQuality(context.Context, *GetQualityRequest) (*GetQualityResponse, error)
}

// UnimplementedQualityServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQualityServiceServer struct{}

func (UnimplementedQualityServiceServer) GetQuality(context.Context, *GetQualityRequest) (*GetQualityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQuality not implemented")
}
func (UnimplementedQualityServiceServer) testEmbeddedByValue() {}

// UnsafeQualityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QualityServiceServer will
// result in compilation errors.
type UnsafeQualityServiceServer interface {
	mustEmbedUnimplementedQualityServiceServer()
}

func RegisterQualityServiceServer(s grpc.ServiceRegistrar, srv QualityServiceServer) {
	// If the following call panics, it indicates UnimplementedQualityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QualityService_ServiceDesc, srv)
}

func _QualityService_GetQuality_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQualityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualityServiceServer).GetQuality(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualityService_GetQuality_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualityServiceServer).GetQuality(ctx, req.(*GetQualityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QualityService_ServiceDesc is the grpc.ServiceDesc for QualityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QualityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recorder.QualityService",
	HandlerType: (*QualityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetQuality",
			Handler:    _QualityService_GetQuality_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recorder.proto",
}
