// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: recorder.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewRecordRequest) Reset() {
	*x = NewRecordRequest{}
	mi := &file_recorder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewRecordRequest) ProtoMessage() {}

func (x *NewRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recorder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewRecordRequest.ProtoReflect.Descriptor instead.
func (*NewRecordRequest) Descriptor() ([]byte, []int) {
	return file_recorder_proto_rawDescGZIP(), []int{0}
}

type NewRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewRecordResponse) Reset() {
	*x = NewRecordResponse{}
	mi := &file_recorder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewRecordResponse) ProtoMessage() {}

func (x *NewRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recorder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewRecordResponse.ProtoReflect.Descriptor instead.
func (*NewRecordResponse) Descriptor() ([]byte, []int) {
	return file_recorder_proto_rawDescGZIP(), []int{1}
}

type GetQualityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReleaseId     int64                  `protobuf:"varint,1,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQualityRequest) Reset() {
	*x = GetQualityRequest{}
	mi := &file_recorder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQualityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQualityRequest) ProtoMessage() {}

func (x *GetQualityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recorder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQualityRequest.ProtoReflect.Descriptor instead.
func (*GetQualityRequest) Descriptor() ([]byte, []int) {
	return file_recorder_proto_rawDescGZIP(), []int{2}
}

func (x *GetQualityRequest) GetReleaseId() int64 {
	if x != nil {
		return x.ReleaseId
	}
	return 0
}

type DiskQuality struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disk          int32                  `protobuf:"varint,1,opt,name=disk,proto3" json:"disk,omitempty"`
	BestRipDate   string                 `protobuf:"bytes,2,opt,name=best_rip_date,json=bestRipDate,proto3" json:"best_rip_date,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskQuality) Reset() {
	*x = DiskQuality{}
	mi := &file_recorder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskQuality) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskQuality) ProtoMessage() {}

func (x *DiskQuality) ProtoReflect() protoreflect.Message {
	mi := &file_recorder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskQuality.ProtoReflect.Descriptor instead.
func (*DiskQuality) Descriptor() ([]byte, []int) {
	return file_recorder_proto_rawDescGZIP(), []int{3}
}

func (x *DiskQuality) GetDisk() int32 {
	if x != nil {
		return x.Disk
	}
	return 0
}

func (x *DiskQuality) GetBestRipDate() string {
	if x != nil {
		return x.BestRipDate
	}
	return ""
}

func (x *DiskQuality) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type GetQualityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         int32                  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	DiskQualities []*DiskQuality         `protobuf:"bytes,2,rep,name=disk_qualities,json=diskQualities,proto3" json:"disk_qualities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQualityResponse) Reset() {
	*x = GetQualityResponse{}
	mi := &file_recorder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQualityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQualityResponse) ProtoMessage() {}

func (x *GetQualityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recorder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQualityResponse.ProtoReflect.Descriptor instead.
func (*GetQualityResponse) Descriptor() ([]byte, []int) {
	return file_recorder_proto_rawDescGZIP(), []int{4}
}

func (x *GetQualityResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GetQualityResponse) GetDiskQualities() []*DiskQuality {
	if x != nil {
		return x.DiskQualities
	}
	return nil
}

var File_recorder_proto protoreflect.FileDescriptor

const file_recorder_proto_rawDesc = "" +
	"\n" +
	"\x0erecorder.proto\x12\brecorder\"\x12\n" +
	"\x10NewRecordRequest\"\x13\n" +
	"\x11NewRecordResponse\"2\n" +
	"\x11GetQualityRequest\x12\x1d\n" +
	"\n" +
	"release_id\x18\x01 \x01(\x03R\treleaseId\"[\n" +
	"\vDiskQuality\x12\x12\n" +
	"\x04disk\x18\x01 \x01(\x05R\x04disk\x12\"\n" +
	"\rbest_rip_date\x18\x02 \x01(\tR\vbestRipDate\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\"h\n" +
	"\x12GetQualityResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x05R\x05score\x12<\n" +
	"\x0edisk_qualities\x18\x02 \x03(\v2\x15.recorder.DiskQualityR\rdiskQualities2T\n" +
	"\fRecordGetter\x12D\n" +
	"\tNewRecord\x12\x1a.recorder.NewRecordRequest\x1a\x1b.recorder.NewRecordResponse2Y\n" +
	"\x0eQualityService\x12G\n" +
	"\n" +
	"GetQuality\x12\x1b.recorder.GetQualityRequest\x1a\x1c.recorder.GetQualityResponseB(Z&github.com/brotherlogic/recorder/protob\x06proto3"

var (
	file_recorder_proto_rawDescOnce sync.Once
	file_recorder_proto_rawDescData []byte
)

func file_recorder_proto_rawDescGZIP() []byte {
	file_recorder_proto_rawDescOnce.Do(func() {
		file_recorder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recorder_proto_rawDesc), len(file_recorder_proto_rawDesc)))
	})
	return file_recorder_proto_rawDescData
}

var file_recorder_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_recorder_proto_goTypes = []any{
	(*NewRecordRequest)(nil),   // 0: recorder.NewRecordRequest
	(*NewRecordResponse)(nil),  // 1: recorder.NewRecordResponse
	(*GetQualityRequest)(nil),  // 2: recorder.GetQualityRequest
	(*DiskQuality)(nil),        // 3: recorder.DiskQuality
	(*GetQualityResponse)(nil), // 4: recorder.GetQualityResponse
}
var file_recorder_proto_depIdxs = []int32{
	3, // 0: recorder.GetQualityResponse.disk_qualities:type_name -> recorder.DiskQuality
	0, // 1: recorder.RecordGetter.NewRecord:input_type -> recorder.NewRecordRequest
	2, // 2: recorder.QualityService.GetQuality:input_type -> recorder.GetQualityRequest
	1, // 3: recorder.RecordGetter.NewRecord:output_type -> recorder.NewRecordResponse
	4, // 4: recorder.QualityService.GetQuality:output_type -> recorder.GetQualityResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_recorder_proto_init() }
func file_recorder_proto_init() {
	if File_recorder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recorder_proto_rawDesc), len(file_recorder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_recorder_proto_goTypes,
		DependencyIndexes: file_recorder_proto_depIdxs,
		MessageInfos:      file_recorder_proto_msgTypes,
	}.Build()
	File_recorder_proto = out.File
	file_recorder_proto_goTypes = nil
	file_recorder_proto_depIdxs = nil
}
